name: 'Configure Docker'
description: 'Set up Docker Buildx and optionally login to Docker Hub'
inputs:
  registry-username:
    description: 'Registry username'
    required: false
  registry-password:
    description: 'Registry password'
    required: false
  registry:
    description: 'Container registry to use'
    required: true
  registry-org:
    description: 'Registry org name'
    required: true
  registry-repo:
    description: 'Registry repo name'
    required: true
  file-env:
    description: 'file env'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Check whether to log in to container registry
      shell: bash
      run: |
        if [[ "${{ github.event_name }}" == "push" && "${{ github.repository }}" == "testing-cirrus-runners/bitcoin" && "${{ github.ref }}" == "refs/heads/master" && -n "${{ inputs.registry-username }}" && -n "${{ inputs.registry-password }}" ]]; then
          echo "REGISTRY_LOGIN=true" >> $GITHUB_ENV
        else
          echo "REGISTRY_LOGIN=false" >> $GITHUB_ENV
        fi

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Container Registry
      uses: docker/login-action@v3
      if: ${{ env.REGISTRY_LOGIN == 'true' }}
      with:
        registry: quay.io
        username: ${{ inputs.registry-username }}
        password: ${{ inputs.registry-password }}

    - name: Set docker build args
      shell: bash
      run: |
        source ${{ inputs.file-env }}
        if [[ "${{ env.REGISTRY_LOGIN }}" == "true" ]]; then
          echo "Logged in to container registry - use cache-to for pushing"
          echo "DOCKER_BUILD_CACHE_ARG=--cache-from=type=registry,ref=${{ inputs.registry}}/${{ inputs.registry-org }}/${{ inputs.registry-repo}}:$CONTAINER_NAME --cache-to=type=registry,ref=${{ inputs.registry}}/${{ inputs.registry-org }}/${{ inputs.registry-repo}}:$CONTAINER_NAME,mode=max --load" >> $GITHUB_ENV
        else
          echo "Not logged in to container registry. Only use cache-from for pulling"
          echo "DOCKER_BUILD_CACHE_ARG=--cache-from=type=registry,ref=${{ inputs.registry}}/${{ inputs.registry-org }}/${{ inputs.registry-repo}}:$CONTAINER_NAME --load" >> $GITHUB_ENV
        fi
