name: 'Save Caches'
description: 'Save ccache, depends sources, and built depends caches'
inputs:
  restore-step-id:
    description: 'Step ID of the restore-caches step'
    required: false
    default: 'restore-caches'

runs:
  using: 'composite'
  steps:
    - name: Save Ccache cache
      uses: WarpBuilds/cache/save@v1
      # Save ccache on Pull Requests
      if: ${{ steps[inputs.restore-step-id].outputs.ccache-cache-hit != 'true' }}
      with:
        path: ${{ env.CCACHE_DIR }}
        key: ccache-${{ github.job }}-${{ github.ref_name }}-${{ github.run_id }}

    - name: Save depends sources cache
      uses: WarpBuilds/cache/save@v1
      if: ${{ (github.event_name != 'pull_request') && steps[inputs.restore-step-id].outputs.depends-sources-cache-hit != 'true' }}
      with:
        path: ${{ env.SOURCES_PATH }}
        key: depends-sources-${{ hashFiles('depends/**') }}

    - name: Save built depends cache
      uses: WarpBuilds/cache/save@v1
      if: ${{ (github.event_name != 'pull_request') && steps[inputs.restore-step-id].outputs.depends-built-cache-hit != 'true' }}
      with:
        path: ${{ env.BASE_CACHE }}
        key: depends-built-${{ github.job }}-${{ hashFiles('depends/**') }}-${{ github.run_id }}
