name: Parallel Bandwidth Test

on:
  workflow_dispatch:

jobs:
  bandwidth-test:
    name: Bandwidth Test ${{ matrix.job_id }}
    runs-on: ghcr.io/cirruslabs/ubuntu-runner-amd64:24.04-sm
    strategy:
      matrix:
        job_id: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
    steps:
      - name: Checkout (Dummy)
        uses: actions/checkout@v4

      - name: Build Docker Image and Measure Bandwidth
        run: |
          echo "Starting test job ID ${{ matrix.job_id }}"
          START_TIME=$(date +%s)

          cat <<EOF > Dockerfile
          FROM ubuntu:22.04

          RUN apt-get update && \
              apt-get install -y curl build-essential git python3 && \
              rm -rf /var/lib/apt/lists/*

          # Download large files (e.g., Qt source packages)
          RUN mkdir /downloads && \
              cd /downloads && \
              curl -L -O https://download.qt.io/archive/qt/5.15/5.15.2/single/qt-everywhere-src-5.15.2.tar.xz
          EOF

          docker build . -t bandwidth-test:${{ matrix.job_id }}

          END_TIME=$(date +%s)
          DURATION=$((END_TIME - START_TIME))

          echo "Job ${{ matrix.job_id }} took $DURATION seconds."
